CREATE TABLE collections (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL,
 collection_name VARCHAR(255) NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
 );

 CREATE INDEX IF NOT EXISTS idx_collections_user_id ON collections(user_id);
 CREATE INDEX IF NOT EXISTS idx_collections_created_at ON collections(created_at DESC);

 ALTER TABLE collections
     ADD CONSTRAINT fk_collections_user
     FOREIGN KEY (user_id) REFERENCES users(id);
