CREATE TABLE collection_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id BIGINT NOT NULL,
  post_id BIGINT NOT NULL,
  added_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE collection_entries
  ADD CONSTRAINT uq_collection_post UNIQUE (collection_id, post_id);

CREATE INDEX IF NOT EXISTS idx_collection_entries_collection_id
  ON collection_entries(collection_id);

CREATE INDEX IF NOT EXISTS idx_collection_entries_post_id
  ON collection_entries(post_id);

CREATE INDEX IF NOT EXISTS idx_collection_entries_collection_added_at_desc
  ON collection_entries(collection_id, added_at DESC);

ALTER TABLE collection_entries
  ADD CONSTRAINT fk_collection_entries_collection
  FOREIGN KEY (collection_id) REFERENCES collections(id);

ALTER TABLE collection_entries
  ADD CONSTRAINT fk_collection_entries_post
  FOREIGN KEY (post_id) REFERENCES posts(id);
