CREATE TABLE likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  user_id BIGINT NOT NULL,
  post_id BIGINT NOT NULL
);

ALTER TABLE likes
  ADD CONSTRAINT fk_likes_user
  FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE likes
  ADD CONSTRAINT fk_likes_post
  FOREIGN KEY (post_id) REFERENCES posts(id);

ALTER TABLE likes
  ADD CONSTRAINT uk_likes_user_post
  UNIQUE (user_id, post_id);

CREATE INDEX IF NOT EXISTS idx_likes_user_id ON likes(user_id);
CREATE INDEX IF NOT EXISTS idx_likes_post_id ON likes(post_id);
