# Enable dev-only Flyway seed migration
spring.flyway.locations=classpath:db/migration,classpath:db/migration-dev

# OpenAPI/Swagger Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

aws.s3.enabled=true
